import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useState } from "react";
import { Image, Pressable, ScrollView, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
const PROFILE = "https://lh3.googleusercontent.com/aida-public/AB6AXuCJsRPYBQCHgxBRzPFw66AOkmuy-9AcNt_g2vsX57A8W5WkBn2NTvk8pFMWNVdsTfB9j5-00K7LwDAttKzEqCEUpxz40iWZklmWuCCcnJapH0ozdk-JNtRzP-j3d1u3JqLk8W02FSfkUNj4lT6eT9hyxMflOn3Fk36NJbW9YAjrVawmzPvEb1mC8y_lFK_h3vCesJQSqde1Kmut7D5DynM8blIyQOG-sWzPXphy32YPAxjvirdKML5-PQ";
const PERSONAS = [{ key: "dog", label: "반려견", icon: "paw" as const, color: "#F97316" }, { key: "senior", label: "시니어", icon: "accessibility" as const, color: "#A855F7" }, { key: "stroller", label: "유모차", icon: "happy" as const, color: "#0EA5E9" }];
const MENUS = [{ label: "저장한 코스", icon: "bookmark" as const, color: "bg-[#22C55E]", route: "/(tabs)/profile/bookmark" }, { label: "나의 게시글", icon: "list" as const, color: "bg-[#39B8FD]", route: "/(tabs)/profile/mypost" }, { label: "좋아요한 글", icon: "heart" as const, color: "bg-[#EF4444]", route: "/(tabs)/profile/like" }, { label: "설정", icon: "settings" as const, color: "bg-slate-300", route: "/settings" }];
export default function ProfileScreen() { const [persona, setPersona] = useState("dog"); const [tags, setTags] = useState(["공원 위주", "식수대 있음"]); const toggle = (tag: string) => setTags((v) => v.includes(tag) ? v.filter((x) => x !== tag) : [...v, tag]); return <SafeAreaView className="flex-1 bg-[#F2F7F2]" edges={["top"]}><ScrollView contentContainerClassName="gap-4 p-5 pb-9">
  <View className="flex-row items-center gap-4 rounded-xl bg-[#F9FCF9] p-6 shadow-sm"><View><Image source={{ uri: PROFILE }} className="h-24 w-24 rounded-full border-4 border-slate-100" /><Pressable className="absolute bottom-0 right-0 h-8 w-8 items-center justify-center rounded-full bg-[#22C55E]" onPress={() => router.push("/settings" as never)}><Ionicons name="pencil" size={14} color="#004B1E" /></Pressable></View><View><Text className="text-2xl font-extrabold text-[#191C1D]">산책러</Text><Text className="mt-1 text-[15px] text-slate-600">walker@example.com</Text></View></View>
  <View className="rounded-xl bg-[#F9FCF9] p-4 shadow-sm"><View className="flex-row items-center gap-2"><Ionicons name="person-circle" size={24} color="#22C55E" /><Text className="text-xl font-extrabold text-[#191C1D]">나의 걷기 유형</Text></View><Text className="mb-4 mt-2 text-sm leading-[21px] text-slate-600">맞춤형 경로를 위해 주된 유형을 선택해주세요.</Text><View className="flex-row gap-1">{PERSONAS.map((item) => { const active = persona === item.key; return <Pressable key={item.key} className={`h-24 flex-1 items-center justify-center gap-1 rounded-lg border-2 ${active ? "bg-orange-50" : "border-slate-200 bg-slate-100"}`} style={active ? { borderColor: item.color } : undefined} onPress={() => setPersona(item.key)}><Ionicons name={item.icon} size={31} color={active ? item.color : "#64748B"} /><Text style={active ? { color: item.color } : undefined} className="text-xs font-bold text-slate-600">{item.label}</Text></Pressable>; })}</View></View>
  <View className="rounded-xl bg-[#F9FCF9] p-4 shadow-sm"><View className="flex-row items-center gap-2"><Ionicons name="pricetag" size={22} color="#22C55E" /><Text className="text-xl font-extrabold text-[#191C1D]">관심 태그</Text></View><Text className="mb-4 mt-2 text-sm text-slate-600">선호하는 산책 환경을 알려주세요.</Text><View className="flex-row flex-wrap gap-2">{["공원 위주", "그늘 많은 곳", "평탄한 길", "식수대 있음"].map((tag) => <Pressable key={tag} onPress={() => toggle(tag)} className={`min-h-12 flex-row items-center rounded-full border px-[15px] ${tags.includes(tag) ? "border-[#22C55E] bg-[#22C55E]" : "border-[#BCCBB9] bg-slate-200"}`}><Text className="text-xs font-bold text-[#26372D]">{tag}</Text></Pressable>)}<Pressable className="h-12 w-12 items-center justify-center rounded-full border border-dashed border-slate-500 bg-slate-100"><Ionicons name="add" size={22} color="#64748B" /></Pressable></View></View>
  <View className="overflow-hidden rounded-xl bg-[#F9FCF9] px-4 shadow-sm">{MENUS.map((item, i) => <Pressable key={item.label} className={`min-h-[68px] flex-row items-center gap-4 ${i < MENUS.length - 1 ? "border-b border-slate-200" : ""}`} onPress={() => router.push(item.route as never)}><View className={`h-[38px] w-[38px] items-center justify-center rounded-full ${item.color}`}><Ionicons name={item.icon} size={20} color={item.label === "설정" ? "#475569" : "white"} /></View><Text className="flex-1 text-[17px] text-[#191C1D]">{item.label}</Text><Ionicons name="chevron-forward" size={22} color="#64748B" /></Pressable>)}</View><Pressable className="h-12 items-center justify-center"><Text className="text-sm text-[#BA1A1A]">회원 탈퇴</Text></Pressable>
  </ScrollView></SafeAreaView>; }
