import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useState } from "react";
import { FlatList, Image, Pressable, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

const POSTS = [{ id: "1", user: "건강한하루", time: "2시간 전", image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAe99syyGw6NkbqaoAYXLZYhf3xOBnas6sZ0e07MMtdnHhoD7cSENUqzi8_XLPxG0-5DgF0gLSsUzck5sT1s6T8JREtOzC_q23ZCsXnqAKA5tYraLHH0ghXfoZw101rwAkOxd_PE9I6-4yTKjs_jqz0p42HBjdrB5Zx61hZS9nqQrn8wynTre1O2jum5qy3q3-_gMZ_5-L_vVlDtV9CAA-hoWMrveAUXCRRNht08ceVKtJm-89UDeyWYw", text: "오늘 아침 공원 산책길이 너무 좋았어요. 날씨도 화창하고 걷기 딱 좋은 온도네요. 다들 좋은 하루 보내세요! 🌿", likes: 24, comments: 5 }, { id: "2", user: "유모차라이더", time: "어제", image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDm5gtCiLACjWV3nZmzE6oU_w2PAFpfar_lfnhS7eomevejN0O9Jqem8RVhcz4IHxpwlvWDPEBGmqkhj4jJycX1SNEIZaemSjJbh9N16u_mO-2Uq_RvnapuqbNCj0kYTbDVtQ-tMqs-0gIB2D-RBWmr_VOjxZtm7gH1PkMYToO7z98mfNf8S94p5OgiIyKItFhZWJNX-zX8v_wzDkt_WxJF7AZuxDov68WBF98RUiLY-_kFX-TUKRiafg", text: "이 길은 경사도 완만하고 바닥이 평평해서 유모차 끌고 가기 정말 좋아요! 추천합니다 👍", likes: 128, comments: 12 }];
function Card({ item }: { item: typeof POSTS[number] }) { const [liked, setLiked] = useState(true); return <View className="bg-white pb-6"><View className="flex-row items-center gap-2.5 px-5 py-2"><View className="h-10 w-10 items-center justify-center rounded-full bg-[#DDF8E5]"><Ionicons name="person" size={18} color="#087A3F" /></View><View className="flex-1"><Text className="text-sm font-black text-slate-900">{item.user}</Text><Text className="mt-0.5 text-xs text-[#3D4A3D]">{item.time}</Text></View><Ionicons name="ellipsis-vertical" size={21} color="#768179" /></View><Image source={{ uri: item.image }} className="h-80 w-full bg-slate-200" /><View className="px-5"><View className="h-[50px] flex-row items-center gap-2"><Pressable className="flex-row items-center gap-1" onPress={() => setLiked(!liked)}><Ionicons name={liked ? "heart" : "heart-outline"} size={24} color={liked ? "#22C55E" : "#405047"} /><Text className={`text-sm font-extrabold ${liked ? "text-[#22C55E]" : "text-[#3D4A3D]"}`}>{item.likes - (liked ? 0 : 1)}</Text></Pressable><Ionicons name="chatbubble" size={22} color="#405047" /><Text className="text-sm font-extrabold text-[#3D4A3D]">{item.comments}</Text><View className="flex-1" /><Ionicons name="bookmark" size={23} color="#405047" /></View><Text className="text-[15px] leading-[22px] text-slate-900"><Text className="font-black">{item.user} </Text>{item.text}</Text><Text className="mt-1.5 text-[13px] text-slate-500">댓글 {item.comments}개 모두 보기</Text></View></View>; }
export default function LikedPostsScreen() { return <SafeAreaView className="flex-1 bg-white" edges={["top"]}><View className="h-14 flex-row items-center justify-between bg-white px-5 shadow-sm"><Pressable className="h-11 w-11 justify-center" onPress={() => router.back()}><Ionicons name="arrow-back" size={22} color="#223128" /></Pressable><Text className="text-2xl font-black text-[#006E2F]">좋아요한 글</Text><View className="w-11" /></View><FlatList data={POSTS} keyExtractor={(item) => item.id} renderItem={({ item }) => <Card item={item} />} contentContainerClassName="pb-6" /></SafeAreaView>; }
